
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `proc`=list(
        `type`="software", 
        `author`="Robin, X., Turck, N., Hainard, A., Tiberti, N., Lisacek, F., Sanchez, JC., M\u00FCller, M., Siegert, S., Doering, M., Billings, Z.", 
        `year`=2023, 
        `title`="pROC: Display and Analyze ROC Curves", 
        `publisher`="[R Package]. Retrieved from https://cran.r-project.org/package=pROC", 
        `url`="https://cran.r-project.org/package=pROC"), 
    `akoglu`=list(
        `type`="article", 
        `author`="Ako\u011Flu, H.", 
        `year`=2022, 
        `title`="User's guide to sample size estimation in diagnostic accuracy studies", 
        `publisher`="Turk J Emerg Med 22:177-85", 
        `url`="https://turkjemergmed.com/abstract/811"))
