
# This file is automatically generated, you probably don't want to edit this

cutoffOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cutoffOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            testpos = NULL,
            classVar = NULL,
            event = NULL,
            cutoffs = list(
                list(cutoff=NULL, direction=">=")),
            diagnostic = TRUE,
            relative = FALSE,
            posttest = FALSE,
            pretest = 10,
            fagan = FALSE, ...) {

            super$initialize(
                package="DiagROC",
                name="cutoff",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous",
                    "ordinal",
                    "nominal"))
            private$..testpos <- jmvcore::OptionLevel$new(
                "testpos",
                testpos,
                variable="(dep)")
            private$..classVar <- jmvcore::OptionVariable$new(
                "classVar",
                classVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..event <- jmvcore::OptionLevel$new(
                "event",
                event,
                variable="(classVar)")
            private$..cutoffs <- jmvcore::OptionArray$new(
                "cutoffs",
                cutoffs,
                default=list(
                    list(cutoff=NULL, direction=">=")),
                template=jmvcore::OptionGroup$new(
                    "cutoffs",
                    NULL,
                    elements=list(
                        jmvcore::OptionNumber$new(
                            "cutoff",
                            NULL),
                        jmvcore::OptionList$new(
                            "direction",
                            NULL,
                            options=list(
                                ">=",
                                ">",
                                "<=",
                                "<"),
                            default=">="))))
            private$..diagnostic <- jmvcore::OptionBool$new(
                "diagnostic",
                diagnostic,
                default=TRUE)
            private$..relative <- jmvcore::OptionBool$new(
                "relative",
                relative,
                default=FALSE)
            private$..posttest <- jmvcore::OptionBool$new(
                "posttest",
                posttest,
                default=FALSE)
            private$..pretest <- jmvcore::OptionNumber$new(
                "pretest",
                pretest,
                min=0,
                max=100,
                default=10)
            private$..fagan <- jmvcore::OptionBool$new(
                "fagan",
                fagan,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..testpos)
            self$.addOption(private$..classVar)
            self$.addOption(private$..event)
            self$.addOption(private$..cutoffs)
            self$.addOption(private$..diagnostic)
            self$.addOption(private$..relative)
            self$.addOption(private$..posttest)
            self$.addOption(private$..pretest)
            self$.addOption(private$..fagan)
        }),
    active = list(
        dep = function() private$..dep$value,
        testpos = function() private$..testpos$value,
        classVar = function() private$..classVar$value,
        event = function() private$..event$value,
        cutoffs = function() private$..cutoffs$value,
        diagnostic = function() private$..diagnostic$value,
        relative = function() private$..relative$value,
        posttest = function() private$..posttest$value,
        pretest = function() private$..pretest$value,
        fagan = function() private$..fagan$value),
    private = list(
        ..dep = NA,
        ..testpos = NA,
        ..classVar = NA,
        ..event = NA,
        ..cutoffs = NA,
        ..diagnostic = NA,
        ..relative = NA,
        ..posttest = NA,
        ..pretest = NA,
        ..fagan = NA)
)

cutoffResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cutoffResults",
    inherit = jmvcore::Group,
    active = list(
        procedure = function() private$.items[["procedure"]],
        summary = function() private$.items[["summary"]],
        cutoffs = function() private$.items[["cutoffs"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Optimal Cut-off Selection")
            self$add(jmvcore::Html$new(
                options=options,
                name="procedure"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Procedure Summary",
                rows="(dep)",
                visible="(dep)",
                clearWith=list(
                    "dep"),
                columns=list(
                    list(
                        `name`="var", 
                        `type`="text", 
                        `content`="($key)", 
                        `title`="Variable"),
                    list(
                        `name`="type", 
                        `type`="text", 
                        `title`="Type"),
                    list(
                        `name`="n", 
                        `type`="number", 
                        `title`="N"),
                    list(
                        `name`="miss", 
                        `type`="number", 
                        `title`="Missing"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="cutoffs",
                title="Results",
                clearWith=list(
                    "dep"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        contingency = function() private$.items[["contingency"]],
                        diagnostics = function() private$.items[["diagnostics"]],
                        relative = function() private$.items[["relative"]],
                        posttest = function() private$.items[["posttest"]],
                        fagan = function() private$.items[["fagan"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="")
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="contingency",
                                rows=3,
                                title="Contingency Table",
                                clearWith=list(
                                    "dep",
                                    "cutoffs",
                                    "classVar",
                                    "event",
                                    "testpos"),
                                columns=list()))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="diagnostics",
                                title="Diagnostic Accuracy",
                                clearWith=list(
                                    "dep",
                                    "cutoffs",
                                    "classVar",
                                    "event",
                                    "testpos"),
                                visible="(diagnostic)",
                                rows=8,
                                columns=list(
                                    list(
                                        `name`="text", 
                                        `type`="text", 
                                        `title`=""),
                                    list(
                                        `name`="result", 
                                        `type`="text", 
                                        `title`="Result"),
                                    list(
                                        `name`="ci.l", 
                                        `type`="text", 
                                        `title`="Lower", 
                                        `superTitle`="95% Confidence Interval"),
                                    list(
                                        `name`="ci.u", 
                                        `type`="text", 
                                        `title`="Upper", 
                                        `superTitle`="95% Confidence Interval"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="relative",
                                title="Relative Risk and Odds Ratio",
                                clearWith=list(
                                    "dep",
                                    "cutoffs",
                                    "classVar",
                                    "event",
                                    "testpos"),
                                visible="(relative)",
                                rows=5,
                                columns=list(
                                    list(
                                        `name`="text", 
                                        `type`="text", 
                                        `title`=""),
                                    list(
                                        `name`="result", 
                                        `type`="text", 
                                        `title`="Result"),
                                    list(
                                        `name`="ci", 
                                        `type`="text", 
                                        `title`="95% Confidence Interval"),
                                    list(
                                        `name`="z", 
                                        `type`="number", 
                                        `title`="z"),
                                    list(
                                        `name`="p", 
                                        `type`="number", 
                                        `title`="p", 
                                        `format`="zto,pvalue"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="posttest",
                                title="Post-Test Probability",
                                clearWith=list(
                                    "dep",
                                    "cutoffs",
                                    "classVar",
                                    "event",
                                    "testpos",
                                    "pretest"),
                                visible="(posttest)",
                                rows=2,
                                columns=list(
                                    list(
                                        `name`="text", 
                                        `title`="", 
                                        `type`="text"),
                                    list(
                                        `name`="result", 
                                        `title`="Post-Test Probability", 
                                        `type`="number", 
                                        `format`="pc"))))
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="fagan",
                                title="Fagan Nomogram",
                                clearWith=list(
                                    "dep",
                                    "cutoffs",
                                    "classVar",
                                    "event",
                                    "testpos",
                                    "pretest"),
                                width=450,
                                height=500,
                                visible="(posttest && fagan)",
                                renderFun=".plot"))}))$new(options=options)))}))

cutoffBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cutoffBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiagROC",
                name = "cutoff",
                version = c(1,0,0),
                options = options,
                results = cutoffResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Optimal Cut-off Selection
#'
#' 
#' @param data .
#' @param dep .
#' @param testpos .
#' @param classVar .
#' @param event .
#' @param cutoffs .
#' @param diagnostic .
#' @param relative .
#' @param posttest .
#' @param pretest .
#' @param fagan .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$procedure} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cutoffs} \tab \tab \tab \tab \tab an array of groups \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
cutoff <- function(
    data,
    dep,
    testpos,
    classVar,
    event,
    cutoffs = list(
                list(cutoff=NULL, direction=">=")),
    diagnostic = TRUE,
    relative = FALSE,
    posttest = FALSE,
    pretest = 10,
    fagan = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cutoff requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(classVar)) classVar <- jmvcore::resolveQuo(jmvcore::enquo(classVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(classVar), classVar, NULL))

    for (v in classVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- cutoffOptions$new(
        dep = dep,
        testpos = testpos,
        classVar = classVar,
        event = event,
        cutoffs = cutoffs,
        diagnostic = diagnostic,
        relative = relative,
        posttest = posttest,
        pretest = pretest,
        fagan = fagan)

    analysis <- cutoffClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

