
# This file is automatically generated, you probably don't want to edit this

manualOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "manualOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            tp = 95,
            fp = 5,
            fn = 20,
            tn = 80,
            diagnostic = TRUE,
            relative = FALSE,
            posttest = FALSE,
            pretest = 10,
            fagan = FALSE, ...) {

            super$initialize(
                package="DiagROC",
                name="manual",
                requiresData=FALSE,
                ...)

            private$..tp <- jmvcore::OptionNumber$new(
                "tp",
                tp,
                default=95)
            private$..fp <- jmvcore::OptionNumber$new(
                "fp",
                fp,
                default=5)
            private$..fn <- jmvcore::OptionNumber$new(
                "fn",
                fn,
                default=20)
            private$..tn <- jmvcore::OptionNumber$new(
                "tn",
                tn,
                default=80)
            private$..diagnostic <- jmvcore::OptionBool$new(
                "diagnostic",
                diagnostic,
                default=TRUE)
            private$..relative <- jmvcore::OptionBool$new(
                "relative",
                relative,
                default=FALSE)
            private$..posttest <- jmvcore::OptionBool$new(
                "posttest",
                posttest,
                default=FALSE)
            private$..pretest <- jmvcore::OptionNumber$new(
                "pretest",
                pretest,
                min=0,
                max=100,
                default=10)
            private$..fagan <- jmvcore::OptionBool$new(
                "fagan",
                fagan,
                default=FALSE)

            self$.addOption(private$..tp)
            self$.addOption(private$..fp)
            self$.addOption(private$..fn)
            self$.addOption(private$..tn)
            self$.addOption(private$..diagnostic)
            self$.addOption(private$..relative)
            self$.addOption(private$..posttest)
            self$.addOption(private$..pretest)
            self$.addOption(private$..fagan)
        }),
    active = list(
        tp = function() private$..tp$value,
        fp = function() private$..fp$value,
        fn = function() private$..fn$value,
        tn = function() private$..tn$value,
        diagnostic = function() private$..diagnostic$value,
        relative = function() private$..relative$value,
        posttest = function() private$..posttest$value,
        pretest = function() private$..pretest$value,
        fagan = function() private$..fagan$value),
    private = list(
        ..tp = NA,
        ..fp = NA,
        ..fn = NA,
        ..tn = NA,
        ..diagnostic = NA,
        ..relative = NA,
        ..posttest = NA,
        ..pretest = NA,
        ..fagan = NA)
)

manualResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "manualResults",
    inherit = jmvcore::Group,
    active = list(
        contingency = function() private$.items[["contingency"]],
        diagnostics = function() private$.items[["diagnostics"]],
        relative = function() private$.items[["relative"]],
        posttest = function() private$.items[["posttest"]],
        fagan = function() private$.items[["fagan"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Manual Calculator")
            self$add(jmvcore::Table$new(
                options=options,
                name="contingency",
                rows=3,
                title="Contingency Table",
                clearWith=list(
                    "tp",
                    "fp",
                    "tn",
                    "fn"),
                columns=list(
                    list(
                        `name`="ptext", 
                        `type`="text", 
                        `format`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="stext", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="refPos", 
                        `type`="number", 
                        `title`="Positive", 
                        `superTitle`="Reference Test / Disease"),
                    list(
                        `name`="refNeg", 
                        `type`="number", 
                        `title`="Negative", 
                        `superTitle`="Reference Test / Disease"),
                    list(
                        `name`="total", 
                        `type`="number", 
                        `title`="Total"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="diagnostics",
                title="Diagnostic Accuracy",
                clearWith=list(
                    "tp",
                    "fp",
                    "tn",
                    "fn"),
                visible="(diagnostic)",
                rows=8,
                columns=list(
                    list(
                        `name`="text", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="result", 
                        `type`="text", 
                        `title`="Result"),
                    list(
                        `name`="ci.l", 
                        `type`="text", 
                        `title`="Lower", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="ci.u", 
                        `type`="text", 
                        `title`="Upper", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="relative",
                title="Relative Risk and Odds Ratio",
                clearWith=list(
                    "tp",
                    "fp",
                    "tn",
                    "fn"),
                visible="(relative)",
                rows=5,
                columns=list(
                    list(
                        `name`="text", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="result", 
                        `type`="text", 
                        `title`="Result"),
                    list(
                        `name`="ci", 
                        `type`="text", 
                        `title`="95% CI"),
                    list(
                        `name`="z", 
                        `type`="number", 
                        `title`="z"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `title`="p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="posttest",
                title="Post-Test Probability",
                clearWith=list(
                    "tp",
                    "tn",
                    "fn",
                    "tn",
                    "pretest"),
                visible="(posttest)",
                rows=2,
                columns=list(
                    list(
                        `name`="text", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="result", 
                        `title`="Post-Test Probability", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="fagan",
                title="Fagan Nomogram",
                clearWith=list(
                    "tp",
                    "tn",
                    "fn",
                    "tn",
                    "pretest"),
                width=450,
                height=500,
                visible="(posttest && fagan)",
                renderFun=".plot"))}))

manualBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "manualBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiagROC",
                name = "manual",
                version = c(1,0,0),
                options = options,
                results = manualResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Manual Calculator
#'
#' 
#' @param tp .
#' @param fp .
#' @param fn .
#' @param tn .
#' @param diagnostic .
#' @param relative .
#' @param posttest .
#' @param pretest .
#' @param fagan .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$contingency} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$relative} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$posttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fagan} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$contingency$asDF}
#'
#' \code{as.data.frame(results$contingency)}
#'
#' @export
manual <- function(
    tp = 95,
    fp = 5,
    fn = 20,
    tn = 80,
    diagnostic = TRUE,
    relative = FALSE,
    posttest = FALSE,
    pretest = 10,
    fagan = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("manual requires jmvcore to be installed (restart may be required)")


    options <- manualOptions$new(
        tp = tp,
        fp = fp,
        fn = fn,
        tn = tn,
        diagnostic = diagnostic,
        relative = relative,
        posttest = posttest,
        pretest = pretest,
        fagan = fagan)

    analysis <- manualClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

