
# This file is automatically generated, you probably don't want to edit this

rocOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            classVar = NULL,
            eventLevel = NULL,
            compareRoc = FALSE,
            showDiagnostics = TRUE,
            showCoords = FALSE,
            showAllCoords = FALSE,
            displayCurves = TRUE,
            combineCurves = TRUE,
            cTP = FALSE,
            cFP = FALSE,
            cFN = FALSE,
            cTN = FALSE,
            cPPV = FALSE,
            cNPV = FALSE,
            cPLR = FALSE,
            cNLR = FALSE,
            cAcc = FALSE,
            cPrev = FALSE,
            cF1 = FALSE,
            cPoints = FALSE,
            cABLine = TRUE,
            cGridLine = TRUE,
            pWidth = 450,
            pHeight = 350, ...) {

            super$initialize(
                package="DiagROC",
                name="roc",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..classVar <- jmvcore::OptionVariable$new(
                "classVar",
                classVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..eventLevel <- jmvcore::OptionLevel$new(
                "eventLevel",
                eventLevel,
                variable="(classVar)")
            private$..compareRoc <- jmvcore::OptionBool$new(
                "compareRoc",
                compareRoc,
                default=FALSE)
            private$..showDiagnostics <- jmvcore::OptionBool$new(
                "showDiagnostics",
                showDiagnostics,
                default=TRUE)
            private$..showCoords <- jmvcore::OptionBool$new(
                "showCoords",
                showCoords,
                default=FALSE)
            private$..showAllCoords <- jmvcore::OptionBool$new(
                "showAllCoords",
                showAllCoords,
                default=FALSE)
            private$..displayCurves <- jmvcore::OptionBool$new(
                "displayCurves",
                displayCurves,
                default=TRUE)
            private$..combineCurves <- jmvcore::OptionBool$new(
                "combineCurves",
                combineCurves,
                default=TRUE)
            private$..cTP <- jmvcore::OptionBool$new(
                "cTP",
                cTP,
                default=FALSE)
            private$..cFP <- jmvcore::OptionBool$new(
                "cFP",
                cFP,
                default=FALSE)
            private$..cFN <- jmvcore::OptionBool$new(
                "cFN",
                cFN,
                default=FALSE)
            private$..cTN <- jmvcore::OptionBool$new(
                "cTN",
                cTN,
                default=FALSE)
            private$..cPPV <- jmvcore::OptionBool$new(
                "cPPV",
                cPPV,
                default=FALSE)
            private$..cNPV <- jmvcore::OptionBool$new(
                "cNPV",
                cNPV,
                default=FALSE)
            private$..cPLR <- jmvcore::OptionBool$new(
                "cPLR",
                cPLR,
                default=FALSE)
            private$..cNLR <- jmvcore::OptionBool$new(
                "cNLR",
                cNLR,
                default=FALSE)
            private$..cAcc <- jmvcore::OptionBool$new(
                "cAcc",
                cAcc,
                default=FALSE)
            private$..cPrev <- jmvcore::OptionBool$new(
                "cPrev",
                cPrev,
                default=FALSE)
            private$..cF1 <- jmvcore::OptionBool$new(
                "cF1",
                cF1,
                default=FALSE)
            private$..cPoints <- jmvcore::OptionBool$new(
                "cPoints",
                cPoints,
                default=FALSE)
            private$..cABLine <- jmvcore::OptionBool$new(
                "cABLine",
                cABLine,
                default=TRUE)
            private$..cGridLine <- jmvcore::OptionBool$new(
                "cGridLine",
                cGridLine,
                default=TRUE)
            private$..pWidth <- jmvcore::OptionNumber$new(
                "pWidth",
                pWidth,
                default=450,
                min=300,
                max=700)
            private$..pHeight <- jmvcore::OptionNumber$new(
                "pHeight",
                pHeight,
                default=350,
                min=300,
                max=700)

            self$.addOption(private$..deps)
            self$.addOption(private$..classVar)
            self$.addOption(private$..eventLevel)
            self$.addOption(private$..compareRoc)
            self$.addOption(private$..showDiagnostics)
            self$.addOption(private$..showCoords)
            self$.addOption(private$..showAllCoords)
            self$.addOption(private$..displayCurves)
            self$.addOption(private$..combineCurves)
            self$.addOption(private$..cTP)
            self$.addOption(private$..cFP)
            self$.addOption(private$..cFN)
            self$.addOption(private$..cTN)
            self$.addOption(private$..cPPV)
            self$.addOption(private$..cNPV)
            self$.addOption(private$..cPLR)
            self$.addOption(private$..cNLR)
            self$.addOption(private$..cAcc)
            self$.addOption(private$..cPrev)
            self$.addOption(private$..cF1)
            self$.addOption(private$..cPoints)
            self$.addOption(private$..cABLine)
            self$.addOption(private$..cGridLine)
            self$.addOption(private$..pWidth)
            self$.addOption(private$..pHeight)
        }),
    active = list(
        deps = function() private$..deps$value,
        classVar = function() private$..classVar$value,
        eventLevel = function() private$..eventLevel$value,
        compareRoc = function() private$..compareRoc$value,
        showDiagnostics = function() private$..showDiagnostics$value,
        showCoords = function() private$..showCoords$value,
        showAllCoords = function() private$..showAllCoords$value,
        displayCurves = function() private$..displayCurves$value,
        combineCurves = function() private$..combineCurves$value,
        cTP = function() private$..cTP$value,
        cFP = function() private$..cFP$value,
        cFN = function() private$..cFN$value,
        cTN = function() private$..cTN$value,
        cPPV = function() private$..cPPV$value,
        cNPV = function() private$..cNPV$value,
        cPLR = function() private$..cPLR$value,
        cNLR = function() private$..cNLR$value,
        cAcc = function() private$..cAcc$value,
        cPrev = function() private$..cPrev$value,
        cF1 = function() private$..cF1$value,
        cPoints = function() private$..cPoints$value,
        cABLine = function() private$..cABLine$value,
        cGridLine = function() private$..cGridLine$value,
        pWidth = function() private$..pWidth$value,
        pHeight = function() private$..pHeight$value),
    private = list(
        ..deps = NA,
        ..classVar = NA,
        ..eventLevel = NA,
        ..compareRoc = NA,
        ..showDiagnostics = NA,
        ..showCoords = NA,
        ..showAllCoords = NA,
        ..displayCurves = NA,
        ..combineCurves = NA,
        ..cTP = NA,
        ..cFP = NA,
        ..cFN = NA,
        ..cTN = NA,
        ..cPPV = NA,
        ..cNPV = NA,
        ..cPLR = NA,
        ..cNLR = NA,
        ..cAcc = NA,
        ..cPrev = NA,
        ..cF1 = NA,
        ..cPoints = NA,
        ..cABLine = NA,
        ..cGridLine = NA,
        ..pWidth = NA,
        ..pHeight = NA)
)

rocResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocResults",
    inherit = jmvcore::Group,
    active = list(
        combinedCurve = function() private$.items[["combinedCurve"]],
        auc = function() private$.items[["auc"]],
        delong = function() private$.items[["delong"]],
        varStats = function() private$.items[["varStats"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ROC Analysis")
            self$add(jmvcore::Image$new(
                options=options,
                name="combinedCurve",
                title="Combined ROC Curves",
                visible="(displayCurves && combineCurves)",
                clearWith=list(
                    "deps",
                    "classVar",
                    "eventLevel",
                    "cPoints",
                    "cABLine",
                    "cGridLine",
                    "pWidth",
                    "pHeight"),
                width=450,
                height=350,
                renderFun=".plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="auc",
                title="ROC Curve Summary",
                rows="(deps)",
                refs="proc",
                clearWith=list(
                    "classVar",
                    "eventLevel"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="area", 
                        `title`="AUC", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Std. Error", 
                        `type`="number"),
                    list(
                        `name`="lowerCi", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upperCi", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="delong",
                title="Pairwise AUC Comparisons (DeLong's Test)",
                rows=0,
                refs="proc",
                visible=FALSE,
                clearWith=list(
                    "deps",
                    "classVar"),
                columns=list(
                    list(
                        `name`="pair", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="diff", 
                        `title`="AUC Difference", 
                        `type`="number"),
                    list(
                        `name`="ci.l", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="ci.u", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="stat", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="pvalue"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="varStats",
                items="(deps)",
                title="Variables",
                clearWith=list(
                    "showAllCoords"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        curve = function() private$.items[["curve"]],
                        coords = function() private$.items[["coords"]],
                        contingency = function() private$.items[["contingency"]],
                        diagnostics = function() private$.items[["diagnostics"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="($key)",
                                title="($key)")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="curve",
                                visible="(displayCurves && !combineCurves)",
                                title="ROC Curve: $key",
                                width=450,
                                height=350,
                                renderFun=".plot",
                                clearWith=list(
                                    "cPoints",
                                    "cABLine",
                                    "cGridLine",
                                    "pWidth",
                                    "pHeight")))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="coords",
                                title="Cut-off Coordinates: $key",
                                rows=0,
                                visible="(showCoords)",
                                clearWith=list(
                                    "classVar",
                                    "event"),
                                columns=list(
                                    list(
                                        `name`="threshold", 
                                        `title`="Cut-off", 
                                        `type`="text"),
                                    list(
                                        `name`="sensitivity", 
                                        `title`="Sensitivity", 
                                        `type`="number", 
                                        `format`="pc"),
                                    list(
                                        `name`="specificity", 
                                        `title`="Specificity", 
                                        `type`="number", 
                                        `format`="pc"),
                                    list(
                                        `name`="tp", 
                                        `title`="TP", 
                                        `type`="integer", 
                                        `visible`="(cTP)"),
                                    list(
                                        `name`="fp", 
                                        `title`="FP", 
                                        `type`="integer", 
                                        `visible`="(cFP)"),
                                    list(
                                        `name`="tn", 
                                        `title`="TN", 
                                        `type`="integer", 
                                        `visible`="(cTN)"),
                                    list(
                                        `name`="fn", 
                                        `title`="FN", 
                                        `type`="integer", 
                                        `visible`="(cFN)"),
                                    list(
                                        `name`="ppv", 
                                        `title`="PPV", 
                                        `type`="number", 
                                        `visible`="(cPPV)", 
                                        `format`="pc"),
                                    list(
                                        `name`="npv", 
                                        `title`="NPV", 
                                        `type`="number", 
                                        `visible`="(cNPV)", 
                                        `format`="pc"),
                                    list(
                                        `name`="plr", 
                                        `title`="PLR", 
                                        `type`="number", 
                                        `visible`="(cPLR)"),
                                    list(
                                        `name`="nlr", 
                                        `title`="NLR", 
                                        `type`="number", 
                                        `visible`="(cNLR)"),
                                    list(
                                        `name`="acc", 
                                        `title`="Accuracy", 
                                        `type`="number", 
                                        `visible`="(cAcc)", 
                                        `format`="pc"),
                                    list(
                                        `name`="prev", 
                                        `title`="Prevalence", 
                                        `type`="number", 
                                        `visible`="(cPrev)", 
                                        `format`="pc"),
                                    list(
                                        `name`="f1", 
                                        `title`="F1 Score", 
                                        `type`="number", 
                                        `visible`="(cF1)"),
                                    list(
                                        `name`="youden", 
                                        `title`="Youden's Index", 
                                        `type`="number"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="contingency",
                                rows=3,
                                title="Contingency Table: $key",
                                visible="(showDiagnostics && !is.null(classVar))",
                                columns=list(),
                                clearWith=list(
                                    "classVar",
                                    "event"),
                                notes=list(
                                    `m`="Based on optimal cut-off (Youden\u2019s Index)")))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="diagnostics",
                                title="Diagnostic Accuracy: $key",
                                visible="(showDiagnostics && !is.null(classVar))",
                                rows=8,
                                clearWith=list(
                                    "classVar",
                                    "event"),
                                columns=list(
                                    list(
                                        `name`="text", 
                                        `type`="text", 
                                        `title`=""),
                                    list(
                                        `name`="result", 
                                        `type`="text", 
                                        `title`="Result"),
                                    list(
                                        `name`="ci.l", 
                                        `type`="text", 
                                        `title`="Lower", 
                                        `superTitle`="95% CI"),
                                    list(
                                        `name`="ci.u", 
                                        `type`="text", 
                                        `title`="Upper", 
                                        `superTitle`="95% CI"))))}))$new(options=options)))}))

rocBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiagROC",
                name = "roc",
                version = c(1,0,0),
                options = options,
                results = rocResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ROC Analysis
#'
#' 
#' @param data .
#' @param deps .
#' @param classVar .
#' @param eventLevel .
#' @param compareRoc .
#' @param showDiagnostics .
#' @param showCoords .
#' @param showAllCoords .
#' @param displayCurves .
#' @param combineCurves .
#' @param cTP .
#' @param cFP .
#' @param cFN .
#' @param cTN .
#' @param cPPV .
#' @param cNPV .
#' @param cPLR .
#' @param cNLR .
#' @param cAcc .
#' @param cPrev .
#' @param cF1 .
#' @param cPoints .
#' @param cABLine .
#' @param cGridLine .
#' @param pWidth .
#' @param pHeight .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$combinedCurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$auc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$delong} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$varStats} \tab \tab \tab \tab \tab an array of groups \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$auc$asDF}
#'
#' \code{as.data.frame(results$auc)}
#'
#' @export
roc <- function(
    data,
    deps,
    classVar,
    eventLevel,
    compareRoc = FALSE,
    showDiagnostics = TRUE,
    showCoords = FALSE,
    showAllCoords = FALSE,
    displayCurves = TRUE,
    combineCurves = TRUE,
    cTP = FALSE,
    cFP = FALSE,
    cFN = FALSE,
    cTN = FALSE,
    cPPV = FALSE,
    cNPV = FALSE,
    cPLR = FALSE,
    cNLR = FALSE,
    cAcc = FALSE,
    cPrev = FALSE,
    cF1 = FALSE,
    cPoints = FALSE,
    cABLine = TRUE,
    cGridLine = TRUE,
    pWidth = 450,
    pHeight = 350) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("roc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(classVar)) classVar <- jmvcore::resolveQuo(jmvcore::enquo(classVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(classVar), classVar, NULL))

    for (v in classVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- rocOptions$new(
        deps = deps,
        classVar = classVar,
        eventLevel = eventLevel,
        compareRoc = compareRoc,
        showDiagnostics = showDiagnostics,
        showCoords = showCoords,
        showAllCoords = showAllCoords,
        displayCurves = displayCurves,
        combineCurves = combineCurves,
        cTP = cTP,
        cFP = cFP,
        cFN = cFN,
        cTN = cTN,
        cPPV = cPPV,
        cNPV = cNPV,
        cPLR = cPLR,
        cNLR = cNLR,
        cAcc = cAcc,
        cPrev = cPrev,
        cF1 = cF1,
        cPoints = cPoints,
        cABLine = cABLine,
        cGridLine = cGridLine,
        pWidth = pWidth,
        pHeight = pHeight)

    analysis <- rocClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

