
# This file is automatically generated, you probably don't want to edit this

samplesizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "singlenew",
            alpha_snew = "0.05",
            ss_snew = 50,
            prev_snew = 30,
            me_snew = 10,
            power_snull = "0.99",
            alpha_snull = "0.05",
            sens1_snull = 95,
            sens0_snull = 90,
            spec1_snull = 85,
            spec0_snull = 80,
            prev_snull = 30,
            power_comp = "0.8",
            alpha_comp = "0.01",
            prop1_comp = 95,
            prop2_comp = 80,
            dismin_comp = 15,
            dismax_comp = 23, ...) {

            super$initialize(
                package="DiagROC",
                name="samplesize",
                requiresData=FALSE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "singlenew",
                    "singlenull",
                    "comparetwo"),
                default="singlenew")
            private$..alpha_snew <- jmvcore::OptionList$new(
                "alpha_snew",
                alpha_snew,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.05")
            private$..ss_snew <- jmvcore::OptionNumber$new(
                "ss_snew",
                ss_snew,
                min=0,
                max=100,
                default=50)
            private$..prev_snew <- jmvcore::OptionNumber$new(
                "prev_snew",
                prev_snew,
                min=0,
                max=100,
                default=30)
            private$..me_snew <- jmvcore::OptionNumber$new(
                "me_snew",
                me_snew,
                min=0,
                max=100,
                default=10)
            private$..power_snull <- jmvcore::OptionList$new(
                "power_snull",
                power_snull,
                options=list(
                    "0.8",
                    "0.9",
                    "0.95",
                    "0.99",
                    "1"),
                default="0.99")
            private$..alpha_snull <- jmvcore::OptionList$new(
                "alpha_snull",
                alpha_snull,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.05")
            private$..sens1_snull <- jmvcore::OptionNumber$new(
                "sens1_snull",
                sens1_snull,
                min=0,
                max=100,
                default=95)
            private$..sens0_snull <- jmvcore::OptionNumber$new(
                "sens0_snull",
                sens0_snull,
                min=0,
                max=100,
                default=90)
            private$..spec1_snull <- jmvcore::OptionNumber$new(
                "spec1_snull",
                spec1_snull,
                min=0,
                max=100,
                default=85)
            private$..spec0_snull <- jmvcore::OptionNumber$new(
                "spec0_snull",
                spec0_snull,
                min=0,
                max=100,
                default=80)
            private$..prev_snull <- jmvcore::OptionNumber$new(
                "prev_snull",
                prev_snull,
                min=0,
                max=100,
                default=30)
            private$..power_comp <- jmvcore::OptionList$new(
                "power_comp",
                power_comp,
                options=list(
                    "0.8",
                    "0.9",
                    "0.95",
                    "0.99",
                    "1"),
                default="0.8")
            private$..alpha_comp <- jmvcore::OptionList$new(
                "alpha_comp",
                alpha_comp,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.01")
            private$..prop1_comp <- jmvcore::OptionNumber$new(
                "prop1_comp",
                prop1_comp,
                min=0,
                max=100,
                default=95)
            private$..prop2_comp <- jmvcore::OptionNumber$new(
                "prop2_comp",
                prop2_comp,
                min=0,
                max=100,
                default=80)
            private$..dismin_comp <- jmvcore::OptionNumber$new(
                "dismin_comp",
                dismin_comp,
                default=15)
            private$..dismax_comp <- jmvcore::OptionNumber$new(
                "dismax_comp",
                dismax_comp,
                default=23)

            self$.addOption(private$..mode)
            self$.addOption(private$..alpha_snew)
            self$.addOption(private$..ss_snew)
            self$.addOption(private$..prev_snew)
            self$.addOption(private$..me_snew)
            self$.addOption(private$..power_snull)
            self$.addOption(private$..alpha_snull)
            self$.addOption(private$..sens1_snull)
            self$.addOption(private$..sens0_snull)
            self$.addOption(private$..spec1_snull)
            self$.addOption(private$..spec0_snull)
            self$.addOption(private$..prev_snull)
            self$.addOption(private$..power_comp)
            self$.addOption(private$..alpha_comp)
            self$.addOption(private$..prop1_comp)
            self$.addOption(private$..prop2_comp)
            self$.addOption(private$..dismin_comp)
            self$.addOption(private$..dismax_comp)
        }),
    active = list(
        mode = function() private$..mode$value,
        alpha_snew = function() private$..alpha_snew$value,
        ss_snew = function() private$..ss_snew$value,
        prev_snew = function() private$..prev_snew$value,
        me_snew = function() private$..me_snew$value,
        power_snull = function() private$..power_snull$value,
        alpha_snull = function() private$..alpha_snull$value,
        sens1_snull = function() private$..sens1_snull$value,
        sens0_snull = function() private$..sens0_snull$value,
        spec1_snull = function() private$..spec1_snull$value,
        spec0_snull = function() private$..spec0_snull$value,
        prev_snull = function() private$..prev_snull$value,
        power_comp = function() private$..power_comp$value,
        alpha_comp = function() private$..alpha_comp$value,
        prop1_comp = function() private$..prop1_comp$value,
        prop2_comp = function() private$..prop2_comp$value,
        dismin_comp = function() private$..dismin_comp$value,
        dismax_comp = function() private$..dismax_comp$value),
    private = list(
        ..mode = NA,
        ..alpha_snew = NA,
        ..ss_snew = NA,
        ..prev_snew = NA,
        ..me_snew = NA,
        ..power_snull = NA,
        ..alpha_snull = NA,
        ..sens1_snull = NA,
        ..sens0_snull = NA,
        ..spec1_snull = NA,
        ..spec0_snull = NA,
        ..prev_snull = NA,
        ..power_comp = NA,
        ..alpha_comp = NA,
        ..prop1_comp = NA,
        ..prop2_comp = NA,
        ..dismin_comp = NA,
        ..dismax_comp = NA)
)

samplesizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeResults",
    inherit = jmvcore::Group,
    active = list(
        whentouse = function() private$.items[["whentouse"]],
        snewresult = function() private$.items[["snewresult"]],
        snullresult = function() private$.items[["snullresult"]],
        compresult = function() private$.items[["compresult"]],
        comments = function() private$.items[["comments"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Size Estimation For Diagnostic Accuracy Studies")
            self$add(jmvcore::Html$new(
                options=options,
                name="whentouse"))
            self$add(jmvcore::Table$new(
                options=options,
                name="snewresult",
                title="Single Test Design, new diagnostic test",
                rows=2,
                visible="(mode == 'singlenew')",
                refs=list(
                    "akoglu"),
                columns=list(
                    list(
                        `name`="text", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="n", 
                        `type`="integer", 
                        `title`="N"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="snullresult",
                title="Single Test Design, comparing the accuracy of a single test to a null value",
                rows=5,
                visible="(mode == 'singlenull')",
                refs=list(
                    "akoglu"),
                columns=list(
                    list(
                        `name`="text", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="cap", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="n", 
                        `type`="integer", 
                        `title`="N"),
                    list(
                        `name`="ncont", 
                        `type`="integer", 
                        `title`="Continuity Correction"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="compresult",
                title="Studies comparing two diagnostic tests",
                rows=5,
                visible="(mode == 'comparetwo')",
                refs=list(
                    "akoglu"),
                columns=list(
                    list(
                        `name`="text1", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="text2", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="cap", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="n", 
                        `type`="integer", 
                        `title`="N"),
                    list(
                        `name`="ncont", 
                        `type`="integer", 
                        `title`="Continuity Correction"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="comments"))}))

samplesizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiagROC",
                name = "samplesize",
                version = c(1,0,0),
                options = options,
                results = samplesizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Sample Size Estimation
#'
#' 
#' @param mode .
#' @param alpha_snew .
#' @param ss_snew .
#' @param prev_snew .
#' @param me_snew .
#' @param power_snull .
#' @param alpha_snull .
#' @param sens1_snull .
#' @param sens0_snull .
#' @param spec1_snull .
#' @param spec0_snull .
#' @param prev_snull .
#' @param power_comp .
#' @param alpha_comp .
#' @param prop1_comp .
#' @param prop2_comp .
#' @param dismin_comp .
#' @param dismax_comp .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$whentouse} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$snewresult} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$snullresult} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$compresult} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comments} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$snewresult$asDF}
#'
#' \code{as.data.frame(results$snewresult)}
#'
#' @export
samplesize <- function(
    mode = "singlenew",
    alpha_snew = "0.05",
    ss_snew = 50,
    prev_snew = 30,
    me_snew = 10,
    power_snull = "0.99",
    alpha_snull = "0.05",
    sens1_snull = 95,
    sens0_snull = 90,
    spec1_snull = 85,
    spec0_snull = 80,
    prev_snull = 30,
    power_comp = "0.8",
    alpha_comp = "0.01",
    prop1_comp = 95,
    prop2_comp = 80,
    dismin_comp = 15,
    dismax_comp = 23) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("samplesize requires jmvcore to be installed (restart may be required)")


    options <- samplesizeOptions$new(
        mode = mode,
        alpha_snew = alpha_snew,
        ss_snew = ss_snew,
        prev_snew = prev_snew,
        me_snew = me_snew,
        power_snull = power_snull,
        alpha_snull = alpha_snull,
        sens1_snull = sens1_snull,
        sens0_snull = sens0_snull,
        spec1_snull = spec1_snull,
        spec0_snull = spec0_snull,
        prev_snull = prev_snull,
        power_comp = power_comp,
        alpha_comp = alpha_comp,
        prop1_comp = prop1_comp,
        prop2_comp = prop2_comp,
        dismin_comp = dismin_comp,
        dismax_comp = dismax_comp)

    analysis <- samplesizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

